trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '14.x'
      checkLatest: true
  - script: yarn install
  - script: yarn lint
  - script: yarn test:coverage
  - script: yarn build
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 
      pathToSources: './src'
      reportDirectory: 'coverage'
      failIfCoverageEmpty: true
