trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '14.x'
      checkLatest: true
  - script: npm ci
    displayName: 'Install dependencies'
  - script: npm run lint
    displayName: 'Lint code'
  - script: npm run test:coverage
    displayName: 'Run tests and collect coverage'
  - script: npm run build
    displayName: 'Build project'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage/cobertura-coverage.xml'
      pathToSources: './src'
      reportDirectory: 'coverage'
      failIfCoverageEmpty: true
